import type {
  BancoReferenciaVideo,
  CreatorConfig,
  CuentaIGDemo,
  CuentaInstagram,
  FacturacionModelo,
  LibraryContent,
  Modelo,
  ReferenciaCuenta,
  ReferenciaVideo,
  VaultEntry,
  VideoEstado,
} from "@/types";

export const sampleModelos: Modelo[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    nombre: "Ana Garcia",
    nombre_real: "Ana Garcia",
    email: "ana@halo.local",
    telefono: "+34 600 100 200",
    activa: true,
    fecha_alta: "2026-08-01",
    notas: "Prioridad tipo 1 y captions cortos.",
    instagram: ["@ana.halo", "@ana.halo.backup"],
    porcentaje_comision: 30,
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    nombre: "Luna Martinez",
    nombre_real: "Luna Martinez",
    email: "luna@halo.local",
    telefono: "+34 600 200 300",
    activa: true,
    fecha_alta: "2026-07-14",
    notas: "Formatos especiales los jueves.",
    instagram: ["@luna.halo"],
    porcentaje_comision: 30,
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    nombre: "Mia Ruiz",
    nombre_real: "Mia Ruiz",
    email: "mia@halo.local",
    telefono: "+34 600 300 400",
    activa: false,
    fecha_alta: "2026-06-20",
    notas: "Cuenta pausada.",
    instagram: ["@mia.halo"],
    porcentaje_comision: 30,
  },
];

export const sampleCuentasInstagram: CuentaInstagram[] = [
  { id: "c1111111-1111-4111-8111-111111111111", modelo_id: sampleModelos[0].id, modelo_nombre: sampleModelos[0].nombre, username: "ana.halo", url: "https://instagram.com/ana.halo", activa: true, metricool_blog_id: "4051234", metricool_estado: "conectada" },
  { id: "c1111111-1111-4111-8111-111111111112", modelo_id: sampleModelos[0].id, modelo_nombre: sampleModelos[0].nombre, username: "ana.halo.backup", url: "https://instagram.com/ana.halo.backup", activa: false, metricool_estado: "no_conectada" },
  { id: "c2222222-2222-4222-8222-222222222221", modelo_id: sampleModelos[1].id, modelo_nombre: sampleModelos[1].nombre, username: "luna.halo", url: "https://instagram.com/luna.halo", activa: true, metricool_estado: "no_conectada" },
  { id: "c3333333-3333-4333-8333-333333333331", modelo_id: sampleModelos[2].id, modelo_nombre: sampleModelos[2].nombre, username: "mia.halo", url: "https://instagram.com/mia.halo", activa: false, metricool_estado: "no_conectada" },
];

export const sampleVideos: LibraryContent[] = [
  {
    id: "aaaaaaa1-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
    modelo_id: sampleModelos[0].id,
    modelo_nombre: sampleModelos[0].nombre,
    r2_key: "editado/ana/2026-09-10/video-tipo1.mp4",
    r2_bucket: "halo-videos",
    filename_original: "ana_tipo1_0910.mp4",
    mimetype: "video/mp4",
    size_bytes: 48600000,
    duracion_seg: 38,
    tipo_video: "tipo1",
    estado: "en_aprobacion",
    notas_editor: "Whisper revisado, subtitulos blancos con sombra.",
    recibido_at: new Date().toISOString(),
    signed_url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    id: "aaaaaaa2-aaaa-4aaa-8aaa-aaaaaaaaaaa2",
    modelo_id: sampleModelos[1].id,
    modelo_nombre: sampleModelos[1].nombre,
    r2_key: "editado/luna/2026-09-10/video-tipo2.mp4",
    r2_bucket: "halo-videos",
    filename_original: "luna_caption_0910.mp4",
    mimetype: "video/mp4",
    size_bytes: 35200000,
    duracion_seg: 26,
    tipo_video: "tipo2",
    estado: "en_aprobacion",
    notas_editor: "Overlay caption centrado, export vertical.",
    recibido_at: new Date(Date.now() - 45 * 60000).toISOString(),
    signed_url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    id: "aaaaaaa3-aaaa-4aaa-8aaa-aaaaaaaaaaa3",
    modelo_id: sampleModelos[0].id,
    modelo_nombre: sampleModelos[0].nombre,
    r2_key: "bruto/ana/2026-09-10/raw.mp4",
    r2_bucket: "halo-videos",
    filename_original: "raw_ana_0910.mp4",
    mimetype: "video/mp4",
    size_bytes: 61200000,
    duracion_seg: 55,
    tipo_video: "sin_clasificar",
    estado: "clasificando",
    notas_editor: "Pendiente thumbnail.",
    recibido_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "aaaaaaa4-aaaa-4aaa-8aaa-aaaaaaaaaaa4",
    modelo_id: sampleModelos[1].id,
    modelo_nombre: sampleModelos[1].nombre,
    r2_key: "editado/luna/2026-09-09/aprobado.mp4",
    r2_bucket: "halo-videos",
    filename_original: "luna_aprobado.mp4",
    mimetype: "video/mp4",
    size_bytes: 41800000,
    duracion_seg: 31,
    tipo_video: "tipo3",
    estado: "aprobado",
    notas_editor: "Reto finalizado.",
    drive_url: "https://drive.google.com/",
    recibido_at: new Date(Date.now() - 25 * 3600000).toISOString(),
    aprobado_at: new Date(Date.now() - 20 * 3600000).toISOString(),
  },
];

export const sampleFacturacion: FacturacionModelo[] = [
  {
    id: "f1111111-1111-4111-8111-111111111111",
    modelo_id: sampleModelos[0].id,
    modelo_nombre: sampleModelos[0].nombre,
    periodo_inicio: "2026-09-01",
    periodo_fin: "2026-09-30",
    ingresos_brutos: 18400,
    porcentaje_comision: 30,
    comision_agencia: 5520,
    neto_modelo: 12880,
    estado_cobro: "pendiente",
  },
  {
    id: "f2222222-2222-4222-8222-222222222222",
    modelo_id: sampleModelos[1].id,
    modelo_nombre: sampleModelos[1].nombre,
    periodo_inicio: "2026-09-01",
    periodo_fin: "2026-09-30",
    ingresos_brutos: 22150,
    porcentaje_comision: 30,
    comision_agencia: 6645,
    neto_modelo: 15505,
    estado_cobro: "cobrado",
    fecha_cobro: "2026-09-08",
  },
  {
    id: "f3333333-3333-4333-8333-333333333333",
    modelo_id: sampleModelos[2].id,
    modelo_nombre: sampleModelos[2].nombre,
    periodo_inicio: "2026-09-01",
    periodo_fin: "2026-09-30",
    ingresos_brutos: 7600,
    porcentaje_comision: 30,
    comision_agencia: 2280,
    neto_modelo: 5320,
    estado_cobro: "atrasado",
  },
];

export const sampleVaultEntries: VaultEntry[] = [
  {
    id: "v1111111-1111-4111-8111-111111111111",
    nombre: "OnlyFans Ana",
    categoria: "of_credentials",
    descripcion: "Cuenta principal de Ana Garcia",
    modelo_id: sampleModelos[0].id,
    created_at: "2026-09-01T10:00:00Z",
  },
  {
    id: "v2222222-2222-4222-8222-222222222222",
    nombre: "Bot Telegram",
    categoria: "telegram",
    descripcion: "Token bot produccion",
    created_at: "2026-09-02T10:00:00Z",
  },
  {
    id: "v3333333-3333-4333-8333-333333333333",
    nombre: "R2 Halo Videos",
    categoria: "api_key",
    descripcion: "Access key Cloudflare R2",
    created_at: "2026-09-03T10:00:00Z",
  },
];

const DEMO_BIOS = [
  ["Enfermera 💉", "Un poco patosa 🤷"],
  ["Formatos especiales los jueves", "Amante del cafe ☕"],
  ["Cuenta secundaria", "Contenido de respaldo"],
  ["Cuenta pausada temporalmente"],
];

export const sampleCreatorConfigs: CreatorConfig[] = [
  {
    modelo_id: sampleModelos[0].id,
    persona_name: "Ana",
    age: 24,
    origin: "España",
    lives_in_country: "España",
    lives_in_city: "Madrid",
    timezone: "Europe/Madrid",
    primary_language: "Español",
    other_languages: ["Inglés"],
    regional_flavor: "Español de España",
    archetype: "Girl next door",
    capitalization: "Todo en minusculas",
    unique_details: "Usa 'guapo', 'cielo' y emojis con moderacion. Frases cortas.",
    persona_lore:
      "Ana estudio enfermeria y ahora compagina turnos con el contenido. Cercana, autentica y un poco traviesa. Le encanta el cafe por las mananas y hablar de series.",
    account_context: "Suena a una persona real, no a un bot. Frases cortas, tono calido, nunca formal.",
    physical_description: "Morena, ojos marrones, 165cm, tatuaje pequeno en la muneca.",
    hard_limits: ["Anal", "Threesome", "Dom roleplay"],
    other_limits: "",
    topic_limits: "Politica, religion",
    custom_pricing_enabled: true,
    photo_min_price: 25,
    video_min_price: 80,
    video_price_per_minute: 40,
    optional_details: "",
    updated_at: "2026-09-10T10:00:00Z",
  },
];

export const sampleCuentasIGDemo: CuentaIGDemo[] = sampleCuentasInstagram
  .filter((cuenta) => cuenta.activa)
  .map((cuenta, index) => ({
    id: cuenta.id,
    username: cuenta.username,
    modelo_nombre: cuenta.modelo_nombre ?? "",
    avatar_url: null,
    tag: index === 0 ? "principal" : "secundaria",
    metricool_estado: cuenta.metricool_estado ?? "no_conectada",
    publicaciones: 38 - index * 6,
    seguidores: 48600 - index * 12000,
    seguidos: 6 + index * 3,
    bio: DEMO_BIOS[index] ?? DEMO_BIOS[0],
    ganancia_hoy: 120 - index * 20,
    ganancia_7d: 840 - index * 140,
    ganancia_30d: 3600 - index * 600,
    ganancia_90d: 9800 - index * 1600,
    estado: index === 0 ? "activa" : "sin_revisar",
    ultimo_reel: new Date(Date.now() - index * 86400000).toISOString(),
    reels_30d_count: 56 - index * 14,
    reels_7d_count: 27 - index * 7,
    mediana_visitas: 11000 - index * 2500,
    demografia: {
      pct_mujeres: 83 - index * 4,
      pct_hombres: 17 + index * 4,
      tramos: [
        { rango: "25-34", pct: 26 },
        { rango: "35-44", pct: 33 },
        { rango: "45-54", pct: 23 },
        { rango: "menores de 25", pct: 9.9 },
      ],
      ciudades: [
        { ciudad: "Madrid", pct: 18 },
        { ciudad: "Barcelona", pct: 12 },
        { ciudad: "Valencia", pct: 8.1 },
        { ciudad: "Sevilla", pct: 8.1 },
        { ciudad: "Bilbao", pct: 4.9 },
        { ciudad: "Otras", pct: 3.1 },
      ],
      fecha: "2026-09-14",
    },
    reels: Array.from({ length: 8 }).map((_, reelIndex) => ({
      id: `${cuenta.id}-reel-${reelIndex}`,
      thumbnail_url: `https://picsum.photos/seed/${cuenta.username}-${reelIndex}/300/530`,
      visitas: Math.round(45000 / (reelIndex + 1) + index * 1000),
      fecha: new Date(Date.now() - (reelIndex + 1) * 2 * 86400000).toISOString(),
      es_trial: reelIndex >= 6,
    })),
  }));

export const sampleReferenciasCuentas: ReferenciaCuenta[] = [
  {
    id: "r1111111-1111-4111-8111-111111111111",
    username: "trendy.creator",
    categoria: "Lifestyle",
    notas: "Buen ritmo de edicion, revisar transiciones.",
    activa: true,
    favorita: true,
    ultimo_scrape_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    intervalo_dias: 7,
    created_at: "2026-08-15T10:00:00Z",
  },
  {
    id: "r2222222-2222-4222-8222-222222222222",
    username: "viral.reels.daily",
    categoria: "Entretenimiento",
    notas: "Fuente principal de retos/tendencias.",
    activa: true,
    favorita: false,
    ultimo_scrape_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    intervalo_dias: 3,
    created_at: "2026-08-20T10:00:00Z",
  },
];

export const sampleBancoReferencias: BancoReferenciaVideo[] = [
  {
    id: "b1111111-1111-4111-8111-111111111111",
    cuenta_referencia_id: sampleReferenciasCuentas[0].id,
    cuenta_username: sampleReferenciasCuentas[0].username,
    url_referencia: "https://instagram.com/reel/demo1",
    frase: "Si te vas a hacer una manualidad hoy, o te la hiciste, o te...",
    cancion_nombre: "Cancion viral",
    cancion_artista: "Artista X",
    views_referencia: 890000,
    likes_referencia: 42000,
    fecha_publicacion_ref: "2026-09-13",
    origen: "bot",
    created_at: "2026-09-13T09:00:00Z",
  },
  {
    id: "b2222222-2222-4222-8222-222222222222",
    cuenta_referencia_id: sampleReferenciasCuentas[1].id,
    cuenta_username: sampleReferenciasCuentas[1].username,
    url_referencia: "https://instagram.com/reel/demo2",
    frase: "Reto de baile con transicion rapida",
    cancion_nombre: null,
    cancion_artista: null,
    views_referencia: 1450000,
    likes_referencia: 98000,
    fecha_publicacion_ref: "2026-09-08",
    origen: "bot",
    created_at: "2026-09-08T09:00:00Z",
  },
  {
    id: "b3333333-3333-4333-8333-333333333333",
    cuenta_referencia_id: sampleReferenciasCuentas[0].id,
    cuenta_username: sampleReferenciasCuentas[0].username,
    url_referencia: "https://instagram.com/reel/demo3",
    frase: null,
    cancion_nombre: null,
    cancion_artista: null,
    views_referencia: null,
    likes_referencia: null,
    fecha_publicacion_ref: null,
    origen: "manual",
    created_at: "2026-09-14T09:00:00Z",
  },
];

const DEMO_VIDEO_URL = "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4";

export const sampleReferenciasVideos: ReferenciaVideo[] = [
  {
    id: "rv1",
    cuenta_id: sampleReferenciasCuentas[0].id,
    cuenta_username: sampleReferenciasCuentas[0].username,
    video_url: DEMO_VIDEO_URL,
    thumbnail_url: "https://picsum.photos/seed/ref1/300/530",
    descripcion: "Rutina matutina con transicion",
    visitas: 890000,
    likes: 42000,
    fecha_publicacion: "2026-09-13",
    lo_que_pone: "manualidad - la hiciste - un corazoncito - practico",
    palabras_voz: 26,
    mira_camara: true,
    frase_detectada: "Si te vas a hacer una manualidad hoy, o te la hiciste, o te ...",
    sin_formato_marcado: true,
    tags: ["manualidad", "la hiciste", "un corazoncito", "practico"],
    formato_propuesto: "generico_of_propuesta",
    formato_confirmado: null,
    estado_triaje: "pendiente",
  },
  {
    id: "rv2",
    cuenta_id: sampleReferenciasCuentas[0].id,
    cuenta_username: sampleReferenciasCuentas[0].username,
    video_url: DEMO_VIDEO_URL,
    thumbnail_url: "https://picsum.photos/seed/ref2/300/530",
    descripcion: "Outfit check trend",
    visitas: 620000,
    likes: 31000,
    fecha_publicacion: "2026-09-14",
    lo_que_pone: "outfit - de hoy - opiniones?",
    palabras_voz: 18,
    mira_camara: true,
    frase_detectada: "Decidme que os parece este outfit para hoy...",
    sin_formato_marcado: false,
    tags: ["outfit", "de hoy", "opiniones"],
    formato_propuesto: "frases",
    formato_confirmado: null,
    estado_triaje: "pendiente",
  },
  {
    id: "rv3",
    cuenta_id: sampleReferenciasCuentas[1].id,
    cuenta_username: sampleReferenciasCuentas[1].username,
    video_url: DEMO_VIDEO_URL,
    thumbnail_url: "https://picsum.photos/seed/ref3/300/530",
    descripcion: "Reto de baile viral",
    visitas: 1450000,
    likes: 98000,
    fecha_publicacion: "2026-09-08",
    formato_propuesto: "reto_generico",
    formato_confirmado: "reto_generico",
    estado_triaje: "confirmado",
    confirmado_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "rv4",
    cuenta_id: sampleReferenciasCuentas[1].id,
    cuenta_username: sampleReferenciasCuentas[1].username,
    video_url: DEMO_VIDEO_URL,
    thumbnail_url: "https://picsum.photos/seed/ref4/300/530",
    descripcion: "Compilado sin audio claro",
    visitas: 410000,
    likes: 15000,
    fecha_publicacion: "2026-09-10",
    palabras_voz: 0,
    mira_camara: false,
    sin_formato_marcado: true,
    tags: ["sin_audio", "compilado"],
    formato_propuesto: null,
    formato_confirmado: null,
    estado_triaje: "pendiente",
  },
  {
    id: "rv5",
    cuenta_id: sampleReferenciasCuentas[0].id,
    cuenta_username: sampleReferenciasCuentas[0].username,
    video_url: DEMO_VIDEO_URL,
    thumbnail_url: "https://picsum.photos/seed/ref5/300/530",
    descripcion: "Sketch antiguo",
    visitas: 250000,
    likes: 9000,
    fecha_publicacion: "2026-08-20",
    palabras_voz: 0,
    mira_camara: false,
    tags: ["sketch"],
    formato_propuesto: "sketch_sin_hablar",
    formato_confirmado: null,
    estado_triaje: "pendiente",
  },
];

export const pipelineEstados: VideoEstado[] = [
  "recibido",
  "clasificando",
  "en_reparto",
  "editando",
  "en_aprobacion",
  "aprobado",
];
